import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/chunks-components/header";
import Footer from "@/components/chunks-components/footer";
import { CartProvider } from "@/app/context/CartContext";
import { WishlistProvider } from "@/app/context2/WishlistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        <WishlistProvider>
          <Header />
          <div>{children}</div>
          <Footer />
         </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
